import os
from typing import Optional, Dict, Any
from metadata_cleaner.logs.logger import logger
from metadata_cleaner.core.metadata_utils import validate_file_path
from . import exiftool_audio_handler, mutagen_audio_handler, tinytag_audio_handler

class AudioHandler:
    """
    Unified handler for audio metadata operations.
    
    Features:
    - Support for multiple audio formats (MP3, WAV, FLAC, etc.)
    - Automatic tool selection (ExifTool/Mutagen/TinyTag)
    - Metadata extraction and removal
    - File integrity verification
    - Error handling and logging
    """

    def __init__(self, use_exiftool: bool = True):
        """
        Initialize the audio handler.

        Args:
            use_exiftool (bool): Whether to prefer ExifTool over other tools when available.
        """
        self.use_exiftool = use_exiftool and is_exiftool_available()
        self.supported_formats = {'.mp3', '.wav', '.flac', '.ogg', '.aac', '.m4a', '.wma'}

    def is_supported(self, file_path: str) -> bool:
        """Check if the file format is supported."""
        ext = os.path.splitext(file_path)[1].lower()
        return ext in self.supported_formats

    def extract_metadata(self, file_path: str) -> Optional[Dict[str, Any]]:
        """
        Extract metadata from an audio file.

        Args:
            file_path (str): Path to the audio file.

        Returns:
            Optional[Dict[str, Any]]: Extracted metadata or None if extraction fails.
        """
        if not validate_file_path(file_path):
            return None

        if not self.is_supported(file_path):
            logger.error(f"Unsupported audio format: {file_path}")
            return None

        try:
            # Try ExifTool first if available and enabled
            if self.use_exiftool:
                metadata = extract_metadata_exiftool(file_path)
                if metadata:
                    logger.info(f"Metadata extracted using ExifTool: {file_path}")
                    return metadata

            # Try Mutagen next
            metadata = extract_metadata_mutagen(file_path)
            if metadata:
                logger.info(f"Metadata extracted using Mutagen: {file_path}")
                return metadata

            # Fall back to TinyTag (read-only)
            metadata = extract_metadata_tinytag(file_path)
            if metadata:
                logger.info(f"Metadata extracted using TinyTag: {file_path}")
                return metadata

            logger.warning(f"No metadata found in: {file_path}")
            return {}

        except Exception as e:
            logger.error(f"Error extracting metadata from {file_path}: {e}", exc_info=True)
            return None

    def remove_audio_metadata(file_path: str, output_path: Optional[str] = None) -> Optional[str]:
        """
        Removes metadata from audio files using a cascade of methods:
        1. ExifTool method
        2. Mutagen method
        3. TinyTag method (as a fallback)
        
        Parameters:
            file_path (str): Path to the audio file.
            output_path (Optional[str]): Destination path for the cleaned file.
                                        If None, a new file name is generated by appending '_cleaned'
                                        before the file extension.
        
        Returns:
            Optional[str]: The path to the cleaned file if successful; otherwise, None.
        """
        if not os.path.exists(file_path):
            logger.error(f"❌ Audio file not found: {file_path}")
            return None

        if not output_path:
            base, ext = os.path.splitext(file_path)
            output_path = f"{base}_cleaned{ext}"

        # Attempt metadata removal using ExifTool first.
        try:
            result = exiftool_audio_handler.remove_metadata(file_path, output_path)
            if result and os.path.exists(result):
                logger.info(f"✅ Metadata removed successfully using ExifTool: {result}")
                return result
            else:
                logger.warning(f"ExifTool method failed for {file_path}")
        except Exception as e:
            logger.error(f"❌ ExifTool method encountered an error for {file_path}: {e}", exc_info=True)

        # Fall back to using Mutagen.
        try:
            result = mutagen_audio_handler.remove_metadata(file_path, output_path)
            if result and os.path.exists(result):
                logger.info(f"✅ Metadata removed successfully using Mutagen: {result}")
                return result
            else:
                logger.warning(f"Mutagen method failed for {file_path}")
        except Exception as e:
            logger.error(f"❌ Mutagen method encountered an error for {file_path}: {e}", exc_info=True)

        # Finally, try using TinyTag as the last resort.
        try:
            result = tinytag_audio_handler.remove_metadata(file_path, output_path)
            if result and os.path.exists(result):
                logger.info(f"✅ Metadata removed successfully using TinyTag: {result}")
                return result
            else:
                logger.warning(f"TinyTag method failed for {file_path}")
        except Exception as e:
            logger.error(f"❌ TinyTag method encountered an error for {file_path}: {e}", exc_info=True)

        logger.error(f"All audio metadata removal methods failed for {file_path}")
        return None

# Create a default instance
default_handler = AudioHandler()

# Convenience functions using the default handler
def extract_metadata(file_path: str) -> Optional[Dict[str, Any]]:
    """Convenience function to extract metadata using default handler."""
    return default_handler.extract_metadata(file_path)

def remove_audio_metadata(file_path: str, output_path: Optional[str] = None) -> Optional[str]:
    """Convenience function to remove metadata using default handler."""
    return default_handler.remove_audio_metadata(file_path, output_path)
